Simulation Pipelining tools: backward::details::handle< T, Deleter > Class Template Reference
backward::details::handle< T, Deleter > Class Template Reference
#include <backward.hpp>
Public Types
typedef rm_ptr< T >::type & ref_t
typedef const rm_ptr< T >::type & const_ref_t
Public Member Functions
~handle ()
handle ()
handle (T val)
handle (const handle &from)
handle & operator= (const handle &from)
void reset (T new_val)
operator const dummy * () const
T get ()
T release ()
void swap (handle &b)
T operator-> ()
const T operator-> () const
ref_t operator* ()
const_ref_t operator* () const
ref_t operator[] (size_t idx)
T * operator& ()
Member Typedef Documentation
template<typename T, typename Deleter = deleter<void, void*, &::free>> typedef const rm_ptr<T>::type& backward::details::handle< T, Deleter >::const_ref_t
template<typename T, typename Deleter = deleter<void, void*, &::free>> typedef rm_ptr<T>::type& backward::details::handle< T, Deleter >::ref_t
Constructor & Destructor Documentation
template<typename T, typename Deleter = deleter<void, void*, &::free>> backward::details::handle< T, Deleter >::~handle () inline
template<typename T, typename Deleter = deleter<void, void*, &::free>> backward::details::handle< T, Deleter >::handle () inline explicit
template<typename T, typename Deleter = deleter<void, void*, &::free>> backward::details::handle< T, Deleter >::handle (T val) inline explicit
template<typename T, typename Deleter = deleter<void, void*, &::free>> backward::details::handle< T, Deleter >::handle (const handle< T, Deleter > & from) inline explicit
Member Function Documentation
template<typename T, typename Deleter = deleter<void, void*, &::free>> T backward::details::handle< T, Deleter >::get () inline
template<typename T, typename Deleter = deleter<void, void*, &::free>> backward::details::handle< T, Deleter >::operator const dummy * () const inline
template<typename T, typename Deleter = deleter<void, void*, &::free>> T* backward::details::handle< T, Deleter >::operator& () inline
template<typename T, typename Deleter = deleter<void, void*, &::free>> ref_t backward::details::handle< T, Deleter >::operator* () inline
template<typename T, typename Deleter = deleter<void, void*, &::free>> const_ref_t backward::details::handle< T, Deleter >::operator* () const inline
template<typename T, typename Deleter = deleter<void, void*, &::free>> T backward::details::handle< T, Deleter >::operator-> () inline
template<typename T, typename Deleter = deleter<void, void*, &::free>> const T backward::details::handle< T, Deleter >::operator-> () const inline
template<typename T, typename Deleter = deleter<void, void*, &::free>> handle& backward::details::handle< T, Deleter >::operator= (const handle< T, Deleter > & from) inline
template<typename T, typename Deleter = deleter<void, void*, &::free>> ref_t backward::details::handle< T, Deleter >::operator[] (size_t idx) inline
template<typename T, typename Deleter = deleter<void, void*, &::free>> T backward::details::handle< T, Deleter >::release () inline
template<typename T, typename Deleter = deleter<void, void*, &::free>> void backward::details::handle< T, Deleter >::reset (T new_val) inline
template<typename T, typename Deleter = deleter<void, void*, &::free>> void backward::details::handle< T, Deleter >::swap (handle< T, Deleter > & b) inline
Referenced by backward::details::handle< std::ifstream *, details::default_delete< std::ifstream * > >::handle(), backward::details::handle< std::ifstream *, details::default_delete< std::ifstream * > >::operator=(), backward::details::handle< std::ifstream *, details::default_delete< std::ifstream * > >::reset(), and backward::details::handle< std::ifstream *, details::default_delete< std::ifstream * > >::swap().
The documentation for this class was generated from the following file:
backward.hpp