var namespacebackward =
[
    [ "Color", "namespacebackward_1_1Color.html", null ],
    [ "ColorMode", "namespacebackward_1_1ColorMode.html", null ],
    [ "details", "namespacebackward_1_1details.html", "namespacebackward_1_1details" ],
    [ "system_tag", "namespacebackward_1_1system__tag.html", null ],
    [ "trace_resolver_tag", "namespacebackward_1_1trace__resolver__tag.html", null ],
    [ "Trace", "structbackward_1_1Trace.html", "structbackward_1_1Trace" ],
    [ "ResolvedTrace", "structbackward_1_1ResolvedTrace.html", "structbackward_1_1ResolvedTrace" ],
    [ "StackTraceImpl", "classbackward_1_1StackTraceImpl.html", "classbackward_1_1StackTraceImpl" ],
    [ "StackTraceImplBase", "classbackward_1_1StackTraceImplBase.html", "classbackward_1_1StackTraceImplBase" ],
    [ "StackTraceImplHolder", "classbackward_1_1StackTraceImplHolder.html", "classbackward_1_1StackTraceImplHolder" ],
    [ "StackTraceImpl< system_tag::current_tag >", "classbackward_1_1StackTraceImpl_3_01system__tag_1_1current__tag_01_4.html", null ],
    [ "StackTrace", "classbackward_1_1StackTrace.html", null ],
    [ "TraceResolverImpl", "classbackward_1_1TraceResolverImpl.html", null ],
    [ "TraceResolverImpl< system_tag::unknown_tag >", "classbackward_1_1TraceResolverImpl_3_01system__tag_1_1unknown__tag_01_4.html", "classbackward_1_1TraceResolverImpl_3_01system__tag_1_1unknown__tag_01_4" ],
    [ "TraceResolverImplBase", "classbackward_1_1TraceResolverImplBase.html", "classbackward_1_1TraceResolverImplBase" ],
    [ "TraceResolver", "classbackward_1_1TraceResolver.html", null ],
    [ "SourceFile", "classbackward_1_1SourceFile.html", "classbackward_1_1SourceFile" ],
    [ "SnippetFactory", "classbackward_1_1SnippetFactory.html", "classbackward_1_1SnippetFactory" ],
    [ "cfile_streambuf", "classbackward_1_1cfile__streambuf.html", "classbackward_1_1cfile__streambuf" ],
    [ "Colorize", "classbackward_1_1Colorize.html", "classbackward_1_1Colorize" ],
    [ "Printer", "classbackward_1_1Printer.html", "classbackward_1_1Printer" ],
    [ "SignalHandling", "classbackward_1_1SignalHandling.html", "classbackward_1_1SignalHandling" ]
];