Simulation Pipelining tools: pipeline.h File Reference
pipeline.h File Reference
Simulation automation tools repo.
#include <string>
#include <iostream>
#include <thread>
#include <vector>
#include <mutex>
#include <ctime>
#include <chrono>
#include <limits.h>
#include <unistd.h>
#include <sstream>
#include <iomanip>
#include <sys/stat.h>
#include <cstring>
#include <fstream>
#include <atomic>
#include <curl/curl.h>
#include "sys/types.h"
#include "sys/sysinfo.h"
#include "backward-cpp/backward.hpp"
Namespaces
backward
Macros
#define BACKWARD_HAS_DW 1
Functions
int bash (std::string command, int nice=0)
Call the given command in bash.
std::string beautify_duration (std::chrono::seconds input_seconds)
Returns a human-readable string of a duration.
void gs (std::string command, std::string windowName)
Executes GRSISort with given command.
void quit ()
Quits GRSISort when done file appears.
void grsisort (std::string command, std::string windowName)
Executes, then quits, command in GRSISort.
std::string ReplaceString (std::string subject, const std::string &search, const std::string &replace)
Replace all instances of a string in another string with a third string.
bool directoryContains (std::string dir)
Check current directory contains the string provided.
bool directoryCheck (std::string dir)
Check run directory.
bool directoryEmpty (std::string dir)
Check if directory is empty.
int root (std::string command)
Executes command in ROOT.
void Backtrace ()
Prints backtrace to stdout.
void email (std::string destination, std::string message)
Emails user.
void slack (std::string message, std::string key)
Slack Message.
int replaceLineInFile (std::string original, std::string replace, std::string input, std::string output)
Change a line in a file, writing to a new file.
std::string curl (std::string url)
std::string between (std::string const &in, std::string const &before, std::string const &after)
Extract string from between other strings.
std::string urlDecode (const std::string SRC)
URL Decode.
void JARVIS (std::string inbox)
Watch JARVIS front end (Incomplete)
void memoryWatchdog (double fraction)
Out-Of-Memory watchdog program (threadable)
template<typename T >
T random_seed ()
Generates a random seed from /dev/random.
Variables
backward::SignalHandling backward::sh
Singal hander - prints pretty debug output if there is an error.
std::atomic< bool > exitFlag
Bool to tell external threads to exit.
Detailed Description
Simulation automation tools repo.
Author
Connor Bray
Date
23 Feb. 2018
This file contains a variety of useful functions for automating simulation execution.
The following arguments are required to compile: -std=c++11 -lX11 -lXtst -pthread -ldl -ldw -g -lcurl
The following arguments are recommended: -Ofast -Wall
To precompile the header: g++ -std=c++11 -lX11 -lXtst -pthread -ldl -ldw -g -lcurl -Ofast -Wall -c pipeline.h
Macro Definition Documentation
#define BACKWARD_HAS_DW 1
Function Documentation
void Backtrace ()
Prints backtrace to stdout.
Code from https://github.com/bombela/backward-cpp (MIT licenced)
Notes:
Requires libdw-dev.
int bash (std::string command, int nice = 0)
Call the given command in bash.
Call the given command in bash
Arguments
std::string command - Command to run. Note that non-interpreters wrappers like nice may not work with aliased commands.
int nice - nice value to run command at (added to avoid issues with nice not working with aliases). Defualts to zero.
Returns the return value of the given function
Notes:
Your bashrc must be configured to only run commands that require interactivity if interactivity is present, otherwise problems may insue.
Referenced by directoryEmpty(), email(), gs(), quit(), and root().
std::string beautify_duration (std::chrono::seconds input_seconds)
Returns a human-readable string of a duration.
Returns a human-readable string of a duration. Credit to TankorSmash on Stackoverflow for the code provided freely in answer to a question asked by sorush-r
Arguments:
std::chrono::seconds input_seconds - Duration to convert to human readable string.
Returns:
std::string - Human readable time duration.
std::string between (std::string const & in, std::string const & before, std::string const & after)
Extract string from between other strings.
Credit to Christopher Creutzig:StackOverflow
Arguments:
string in - Input string to find in string before - String before target string after - String after target
Return value
Returns target string, the string between before and after in in.
Referenced by JARVIS().
std::string curl (std::string url)
Referenced by JARVIS().
bool directoryCheck (std::string dir)
Check run directory.
Check run directory
Arguments:
string dir - Directory to check if running in.
Notes:
If it is, it returns zero, otherwise it prompts the user if they want to procede anyway or not. Returns 0 if they want to procede and 1 otherwise.
bool directoryContains (std::string dir)
Check current directory contains the string provided.
Check current directory contains the string provided
Arguments:
string dir - Directory to check if contained.
Notes:
If it is, it returns zero, otherwise it prompts the user if they want to procede anyway or not. Returns 0 if they want to procede and 1 otherwise.
bool directoryEmpty (std::string dir)
Check if directory is empty.
Check run directory for files
Arguments:
string dir - Directory to check if running in.
Notes:
If it is, it returns zero, otherwise it prompts the user for how they want to procede. Returns 0 if they want to procede and 1 otherwise.
void email (std::string destination, std::string message)
Emails user.
Email user
Arguments:
string destination - Email to send to string message - Message of Email
Notes:
To email when program is complete, in your main, add the following line: std::atexit(email(destination,message));
Also, please use this sparingly. If any major email providers decide that it is spam, then its going to be broken for everyone on cronos forever.
void grsisort (std::string command, std::string windowName)
Executes, then quits, command in GRSISort.
Executes command in GRSISort
Arguments:
string command - GRSISort command.
string windowName - command terminal name (because keyboard emulation is used to type in command).
Notes:
Runs whichever version of GRSISort is the "default" (AKA the one returned by which grsisort in your bourne shell (sh shell)) To exit, the gs macro must write the command's pid to a file called 'done' so that the quit command knows which to quit.
Vector of treads initiated to simplify rejoining
void gs (std::string command, std::string windowName)
Executes GRSISort with given command.
Executes GRSISort with given command.
Arguments:
string command - GRSISort command.
string windowName - command terminal name (because keyboard emulation is used to type in command).
Referenced by grsisort().
void JARVIS (std::string inbox)
Watch JARVIS front end (Incomplete)
Watches JARVIS bot front end for messages
Notes:
How to use: First, start the bot in a new thread: thread t(JARVIS, <inbox url>); At end of simulation, set exitFlag to 1 (tells thread to exit), then join the thread.
Arguments:
string inbox - Link to webhook inbox (use webhook inbox becaues cronos is behind a firewall). Link should look like this: http://api.webhookinbox.com/i/xxxxxxxx/
void memoryWatchdog (double fraction)
Out-Of-Memory watchdog program (threadable)
Watches the amount of available ram, and kills the program if <n% is remaining (configurable).
Arguments:
double fraction - Fraction of memory remaining to abort if reached.
void quit ()
Quits GRSISort when done file appears.
Quits GRSISort when done file appears
Notes:
The gs macro needs to write its PID to the done file in order for this command to work. For gs commands that exit properly, just create an empty file done to continue.
Continuously looks for file "done" without the quotes. When it appears, it waits a few seconds and quits GRSTsort with the kill command.
This is a workaround for GRSISort's crashing at the end of the simulation. All of the analysis is complete, so data integrity is preserved.
Referenced by grsisort().
template<typename T > T random_seed ()
Generates a random seed from /dev/random.
Generate a random seed from /dev/random
Generating the seed from /dev/random is prefered to generating the seed from the current time because it allows you to start more than one simulation in a second and because /dev/random is cryptographically secure.
Code adapted from that posted by posop on stackoverflow
int replaceLineInFile (std::string original, std::string replace, std::string input, std::string output)
Change a line in a file, writing to a new file.
Change a line in a file, writing to a new file (Modifed from code written by Anton on StackOverflow)
Arguments:
string original - String to replace
string replace - String to replace original with
string input - Filename of input file
string output - Filename of output file
std::string ReplaceString (std::string subject, const std::string & search, const std::string & replace)
Replace all instances of a string in another string with a third string.
Replace all instances of a string in another string with a third string. Credit to Czarek Tomczak on stack overflow for supplying the code in response to a question asked by NullVoxPopuli.
Arguments:
std::string subject - String to do replacements in.
const std::string& search - Substring to replace with the replace string.
const std::string& replace - Substring to replace the search string with.
int root (std::string command)
Executes command in ROOT.
Executes command in ROOT
Arguments:
string command - ROOT command.
void slack (std::string message, std::string key)
Slack Message.
Sends slack message
Arguments:
string message - Message to send
string key - API key - should look something like "https://hooks.slack.com/services/xxxxxxxxx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
Notes:
To use, in your main, add the following line: std::atexit(slack(message,key));
To use, you will need to go to api.slack.com (or request I do so), and get an API hook into whichever DM or channel you want to message.
Referenced by JARVIS().
std::string urlDecode (const std::string SRC)
URL Decode.
Credit to tominko on StackOverflow.
Arguments:
string SRC - String to decode
Return value
Decoded string
Referenced by JARVIS().
Variable Documentation
std::atomic<bool> exitFlag
Bool to tell external threads to exit.